version: '3.8'

services:
  db:
    image: postgres:12
    container_name: our-chat
    restart: always
    environment:
      POSTGRES_USER: beanBag
      POSTGRES_PASSWORD: ${POSTGRESPWD}
    ports:
      - 54320:5432
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
