import Head from 'next/head'
import styles from '../styles/index.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>💖 Our Chat 💖</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative flex h-screen items-center justify-center">
        <div
          className={`absolute inset-0 h-screen bg-slate-50 bg-bottom bg-no-repeat ${styles.bg}`}
        >
          <div
            className="absolute inset-0 bg-[bottom_1px_center] bg-grid-slate-900/[0.04]"
            style={{
              maskImage: 'linear-gradient(to bottom, transparent, black)',
              WebkitMaskImage: 'linear-gradient(to bottom, transparent, black)',
            }}
          />
        </div>

        <div className="relative h-3/4 w-3/5 rounded-2xl border bg-indigo-300 bg-opacity-50 backdrop-blur">
          123
        </div>
      </div>
    </>
  )
}
