import { Button, Form, Input } from 'antd'
import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import styles from '../styles/index.module.css'
import { trpc } from '../utils/trpc'

export default function Home() {
  const hello = trpc.hello.useQuery({ text: 'client' })
  const name = trpc.queryName.useQuery({ text: '734986933@qq.com' })

  if (!hello.data) {
    return <div>Loading.....</div>
  }

  return (
    <>
      <Head>
        <title>💖 Our Chat 💖</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="h-full w-1/2 p-10">
          <div>
            <h1 className="text-6xl font-bold text-violet-400">Hello,</h1>
            <h1 className="text-6xl font-bold text-violet-500">Welcome!</h1>
          </div>
          <div className="mt-16">
            {name.data?.item?.name}
            {name.data?.item?.email}
            <Form layout="vertical">
              <Form.Item label="用户名">
                <Input placeholder="Username" />
              </Form.Item>
              <Form.Item label="密码">
                <Input.Password placeholder="Password" />
              </Form.Item>

              <Form.Item className="mt-20">
                <div className="flex w-full justify-between">
                  <Button
                    type="primary"
                    className="w-2/5 bg-violet-400 hover:!bg-violet-600"
                  >
                    登录 
                  </Button>

                  <Button type="primary" className="w-2/5" disabled>
                    注册 
                  </Button>
                </div>
              </Form.Item>
            </Form>
          </div>
        </div>
        <div
          className={`h-full w-1/2 bg-purple-400 bg-center bg-no-repeat ${styles.loginBg}`}
        />
      </Layout>
    </>
  )
}
